# Reached from all urls.

itemsharing.greeting: "Hello World"

eureka:
  instance:
    perfer-ip-address: false # This was true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
