# Reached from all urls.

itemsharing.greeting: "Hello World"

eureka:
  instance:
    # Necessary for Docker as it doesn't have DNS entries
    prefer-ip-address: true
    ip-address:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.107:8761/eureka/
