spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.H2Dialect"
  datasource:
    url: "jdbc:h2:mem:"
    username: "sa"
    data-password: "sa"

security:
  basic:
    enabled: false

server:
  port: 8081
