server:
  port: 8082

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57InnoDBDialect"
  datasource:
    url: "jdbc:mysql://192.168.0.106:3306/itemsharing?useSSL=false"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.jdbc.Driver"

security:
  basic:
    enabled: false

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.itemsharing: DEBUG
