spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57InnoDBDialect"
  datasource:
    url: "jdbc:mysql://localhost:3306/itemsharing?useSSL=false"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.jdbc.Driver"

security:
  basic:
    enabled: false

server:
  port: 8082
