# Reached from url: http://localhost:8888/userservice/default

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57InnoDBDialect"
  datasource:
    url: "jdbc:mysql://192.168.0.106:3306/itemsharing?useSSL=false"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.jdbc.Driver"

# We set management.security.enabled=false in the client app to make this easy to
# test(by default since Spring Boot 1.5 the Actuator endpoints are secure by default).
# By default you can still access them over JMX if you don’t set the flag.
security:
  basic:
    enabled: false

server:
  port: 8081
